server:
  port: 0 #Assigns a port automatically

#Actuator management path
management:
  context-path: /admin

info:
  name: "Service A"
  description: "Client for service B"

#Enabling actuator endpoints
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: false
    metadataMap:
      hostname: ${vcap.application.application_uris[0]}
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

ribbon:
  eureka:
   enabled: true

serviceB:
    ribbon:
      MaxAutoRetries: 1
      MaxAutoRetriesNextServer: 1
      OkToRetryOnAllOperations: true
      ServerListRefreshInterval: 1000
      NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
